# Generated by Django 4.1.6 on 2024-10-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0013_student_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="contract", name="template_location",),
    ]
