# Generated by Django 4.1.6 on 2024-10-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0014_remove_contract_template_location"),
    ]

    operations = [
        migrations.RemoveField(model_name="contract", name="join_fee_status",),
        migrations.RemoveField(model_name="contract", name="status",),
    ]
