# Generated by Django 4.1.6 on 2024-10-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0015_remove_contract_join_fee_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="join_fee_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
