# Generated by Django 4.1.6 on 2024-12-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0018_remove_student_birthdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Honor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_manager.student",
                    ),
                ),
            ],
        ),
    ]
