# Generated by Django 4.1.6 on 2024-12-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_manager",
            "0020_student_grade_let_student_grade_num_student_lang_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("Лид", "В работе"),
                    ("Int", "Intermediate"),
                    ("При", "Принят"),
                    ("Акт", "Активный"),
                    ("Выб", "Выбыл"),
                ],
                default="Лид",
                max_length=30,
            ),
        ),
    ]
