# Generated by Django 4.1.6 on 2024-12-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0021_alter_student_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="temp_phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("Лид", "В работе"),
                    ("Int", "Intermediate"),
                    ("Акт", "Активный"),
                    ("Выб", "Выбыл"),
                ],
                default="Лид",
                max_length=30,
            ),
        ),
    ]
