# Generated by Django 4.1.6 on 2025-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0023_alter_student_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student", name="leave_date", field=models.DateField(null=True),
        ),
    ]
