# Generated by Django 4.1.6 on 2025-01-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0025_alter_student_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="grade",),
    ]
