# Generated by Django 4.1.6 on 2025-01-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0026_remove_student_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("receiver", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
    ]
