# Generated by Django 4.1.6 on 2025-01-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0027_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="leave_date", new_name="date",
        ),
    ]
