# Generated by Django 4.1.6 on 2025-01-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0028_rename_leave_date_student_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="temp_phone",),
    ]
