# Generated by Django 4.2.20 on 2025-03-29 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0029_remove_student_temp_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="user_manager.student",
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="user_manager.candidate",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[("let", "letter"), ("sta", "status")], max_length=6
                    ),
                ),
                ("let_a", models.CharField(max_length=1, null=True)),
                ("let_b", models.CharField(max_length=1, null=True)),
                ("status_a", models.BooleanField(null=True)),
                ("status_b", models.BooleanField(null=True)),
            ],
        ),
    ]
