# Generated by Django 4.2.20 on 2025-03-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0030_candidate_change"),
    ]

    operations = [
        migrations.RenameField(
            model_name="change", old_name="status_a", new_name="changed_status",
        ),
        migrations.RemoveField(model_name="change", name="status_b",),
    ]
