# Generated by Django 4.2.20 on 2025-03-30 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0031_rename_status_a_change_changed_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="change",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
