# Generated by Django 4.2.20 on 2025-03-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0032_change_date_time"),
    ]

    operations = [
        migrations.DeleteModel(name="Change",),
    ]
