# Generated by Django 4.2.20 on 2025-03-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0033_delete_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[("let", "letter"), ("sta", "status")], max_length=6
                    ),
                ),
                ("let_a", models.CharField(max_length=1, null=True)),
                ("let_b", models.CharField(max_length=1, null=True)),
                ("changed_status", models.BooleanField(null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_manager.candidate",
                    ),
                ),
            ],
        ),
    ]
