# Generated by Django 4.2.20 on 2025-04-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0034_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="student", name="balance", field=models.IntegerField(null=True),
        ),
    ]
