# Generated by Django 4.2.20 on 2025-04-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0035_student_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.CharField(
                choices=[("sch", "school"), ("lyc", "lyceum")],
                default="sch",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="lang",
            field=models.CharField(
                choices=[("Рус", "Русский"), ("Каз", "Казахский")],
                max_length=3,
                null=True,
            ),
        ),
    ]
