# Generated by Django 4.2.20 on 2025-05-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0036_student_school_alter_student_lang"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_num", models.IntegerField(null=True)),
                ("grade_let", models.CharField(max_length=1, null=True)),
                (
                    "curator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_manager.lms_user",
                    ),
                ),
            ],
        ),
    ]
