# Generated by Django 4.2.20 on 2025-05-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0037_grade"),
    ]

    operations = [
        migrations.DeleteModel(name="Document",),
        migrations.RenameField(
            model_name="student", old_name="parent_1", new_name="parent",
        ),
        migrations.RemoveField(model_name="contract", name="signed_location",),
        migrations.RemoveField(model_name="student", name="balance",),
        migrations.AddField(
            model_name="student",
            name="picture",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="lms_user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Админ", "Администрация"),
                    ("ВнСв", "Зам по ВСиРШ"),
                    ("Кур", "Куратор"),
                    ("HR", "Отдел Кадров"),
                ],
                default="Админ",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(name="List_Of_Students",),
    ]
