# Generated by Django 4.2.20 on 2025-05-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_manager",
            "0038_delete_document_rename_parent_1_student_parent_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(old_name="Honor", new_name="Journal",),
    ]
