# Generated by Django 5.2 on 2025-11-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0039_rename_honor_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_let',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Лид', 'В работе'), ('Int', 'Intermediate'), ('Акт', 'Активный'), ('Int_leave', 'Intermediate leave'), ('Арх', 'Архив'), ('Вып', 'Выпускник')], default='Лид', max_length=30),
        ),
    ]
