# Generated by Django 4.2.20 on 2025-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0040_alter_grade_grade_let_alter_grade_grade_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student", name="id", field=models.IntegerField(null=True),
        ),
    ]
