# Generated by Django 4.2.20 on 2025-11-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0041_student_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="change", name="candidate",),
        migrations.DeleteModel(name="Candidate",),
        migrations.DeleteModel(name="Change",),
    ]
