# Generated by Django 4.2.20 on 2025-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0042_remove_change_candidate_delete_candidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="id", field=models.IntegerField(),
        ),
    ]
