# Generated by Django 4.2.20 on 2025-11-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0043_alter_student_id"),
    ]

    operations = [
        migrations.DeleteModel(name="Journal",),
    ]
