# Generated by Django 4.2.20 on 2025-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0044_delete_journal"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="user",),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
