# Generated by Django 4.2.20 on 2025-11-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0046_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="IIN",
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
