# Generated by Django 4.2.20 on 2025-11-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0047_alter_student_iin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
