# Generated by Django 4.1.6 on 2024-10-28 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("iin", models.CharField(max_length=12, unique=True)),
                ("last_name", models.CharField(max_length=40)),
                ("first_name", models.CharField(max_length=30)),
                ("patronim", models.CharField(max_length=40, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Муж", "Мужской"), ("Жен", "Женский")], max_length=10
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("phone_WA", models.CharField(max_length=20)),
                ("exp_salary", models.IntegerField()),
                ("position", models.CharField(max_length=30)),
                ("comment", models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
