# Generated by Django 4.1.6 on 2024-10-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicant", name="comment",),
        migrations.RemoveField(model_name="applicant", name="gender",),
        migrations.RemoveField(model_name="applicant", name="phone_WA",),
        migrations.AddField(
            model_name="applicant",
            name="lang",
            field=models.CharField(
                choices=[("Рус", "Русский"), ("Каз", "Казахский")],
                default="Рус",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="position",
            field=models.CharField(max_length=70),
        ),
    ]
