# Generated by Django 4.1.6 on 2024-10-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0002_remove_applicant_comment_remove_applicant_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicant", name="user",),
        migrations.AlterField(
            model_name="applicant",
            name="iin",
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
