# Generated by Django 4.1.6 on 2024-10-31 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HR", "0003_remove_applicant_user_alter_applicant_iin"),
    ]

    operations = [
        migrations.CreateModel(
            name="HR_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("picture", models.CharField(default="Avatar.png", max_length=150)),
                (
                    "user_type",
                    models.CharField(choices=[("HR", "HR Manager")], max_length=50),
                ),
                ("phone", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
