# Generated by Django 4.1.6 on 2024-11-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0004_hr_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[("Арх", "Архив"), ("Инт", "Интервью"), ("Акт", "Активный")],
                default="Акт",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("interviewers", models.CharField(max_length=200)),
                ("comments", models.CharField(max_length=500)),
                ("salary", models.IntegerField(null=True)),
                ("decision", models.BooleanField()),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="HR.applicant"
                    ),
                ),
            ],
        ),
    ]
