# Generated by Django 4.1.6 on 2024-11-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0005_applicant_status_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="comments",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="decision",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interviewers",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
