# Generated by Django 4.1.6 on 2024-11-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0006_alter_interview_comments_alter_interview_decision_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="interview", name="comments",),
        migrations.AddField(
            model_name="interview",
            name="comment",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="conditions",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
