# Generated by Django 4.1.6 on 2024-11-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0007_remove_interview_comments_interview_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("Арх", "Архив"),
                    ("Инт", "Интервью"),
                    ("Акт", "Активный"),
                    ("Отк", "Отказано"),
                ],
                default="Акт",
                max_length=10,
            ),
        ),
    ]
