# Generated by Django 4.1.6 on 2024-11-14 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0009_alter_applicant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="appl_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
