# Generated by Django 4.1.6 on 2025-02-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0010_applicant_appl_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("salary_status", models.BooleanField()),
                ("salary", models.IntegerField(null=True)),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("exp1", "Без опыта"),
                            ("exp2", "1-2 года"),
                            ("exp3", "3-5 лет"),
                            ("exp4", "Более 5 лет"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
            ],
        ),
    ]
