# Generated by Django 4.1.6 on 2025-02-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0011_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position", name="description", field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="position", name="requirements", field=models.JSONField(),
        ),
    ]
