# Generated by Django 4.1.6 on 2025-02-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0012_alter_position_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position", name="date", field=models.DateField(null=True),
        ),
    ]
