# Generated by Django 4.1.6 on 2025-02-03 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0013_position_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
