# Generated by Django 4.1.6 on 2025-02-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0014_alter_position_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="status",
            field=models.CharField(
                choices=[("act", "Активный"), ("arc", "Архив")],
                default="act",
                max_length=15,
            ),
        ),
    ]
