# Generated by Django 4.1.6 on 2025-02-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0015_position_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[("wait", "Отложено"), ("neg", "Отказано"), ("pos", "Принят")],
                default="wait",
                max_length=15,
            ),
        ),
    ]
