# Generated by Django 4.1.6 on 2025-02-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0016_interview_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[("wait", "Отложено"), ("neg", "Отказано"), ("pos", "Принят")],
                max_length=4,
                null=True,
            ),
        ),
    ]
