# Generated by Django 4.2.20 on 2025-05-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HR", "0017_alter_interview_status"),
    ]

    operations = [
        migrations.DeleteModel(name="HR_User",),
    ]
